"""
Error validator — error normalization compliance checking.

Validates that providers correctly normalize errors into the standard
ToolError format and that write methods raise MockWriteDisabledError
(not arbitrary exceptions, not silently succeeding).

Rules enforced:

  1. Write methods on mock providers MUST raise MockWriteDisabledError.
     No other exception type is acceptable. Silently returning is a
     contract violation — it would indicate writes were accepted.

  2. MockWriteDisabledError must have a Phase 2B gate message.

  3. Failure-mode providers (SimulationConfig with a FailureMode) must
     raise a MockIntegrationError subclass, never a raw Python exception
     (ValueError, KeyError, AttributeError, etc.).

  4. send_email must not exist on the email provider — its absence is
     itself an error normalization rule (ADR: no send capability).

  5. Error instances must carry retryable=True for transient errors
     (RATE_LIMITED, TIMEOUT, UNAVAILABLE) and retryable=False for
     permanent errors (NOT_FOUND, UNAUTHORIZED, FORBIDDEN).

No business logic. No real API calls. Mock data only.
"""

from __future__ import annotations

import datetime
from dataclasses import dataclass, field
from typing import Any

from backend.app.integration.contracts.common import (
    ProviderMode,
    ToolExecutionContext,
)
from backend.app.integration.mocks.errors import (
    MockForbiddenError,
    MockIntegrationError,
    MockNotFoundError,
    MockRateLimitError,
    MockTimeoutError,
    MockUnauthorizedError,
    MockUnavailableError,
    MockWriteDisabledError,
)
from backend.app.integration.mocks.simulation import FailureMode, SimulationConfig

_TEST_CTX = ToolExecutionContext(
    user_id="validator",
    display_name="Validation Runner",
    roles=["adjuster"],
    permissions=["read"],
    correlation_id="err-val-corr",
    trace_id="err-val-trace",
    request_id="err-val-req",
    provider_mode=ProviderMode.MOCK,
    writes_enabled=False,
)

_KNOWN_CLAIM_ID = "CLM-2026-100245"

# Mapping: FailureMode -> expected exception class + expected retryable value
_FAILURE_MODE_EXPECTATIONS: list[tuple[FailureMode, type[MockIntegrationError], bool]] = [
    (FailureMode.NOT_FOUND,    MockNotFoundError,     False),
    (FailureMode.UNAUTHORIZED, MockUnauthorizedError, False),
    (FailureMode.FORBIDDEN,    MockForbiddenError,    False),
    (FailureMode.RATE_LIMITED, MockRateLimitError,    True),
    (FailureMode.TIMEOUT,      MockTimeoutError,      True),
    (FailureMode.UNAVAILABLE,  MockUnavailableError,  True),
]


@dataclass
class ErrorViolation:
    provider_name: str
    check_name: str
    violation_type: str
    detail: str


@dataclass
class ErrorValidationResult:
    provider_name: str
    valid: bool
    violations: list[ErrorViolation] = field(default_factory=list)
    checks_run: int = 0
    checks_passed: int = 0

    @property
    def summary(self) -> str:
        if self.valid:
            return f"PASS ({self.checks_passed}/{self.checks_run} checks)"
        return (
            f"FAIL ({self.checks_passed}/{self.checks_run} checks, "
            f"{len(self.violations)} violation(s))"
        )


# ---------------------------------------------------------------------------
# Write gate validation — claimcenter only (the only provider with writes)
# ---------------------------------------------------------------------------

def _validate_write_gate(
    provider_name: str,
    provider: Any,
    violations: list[ErrorViolation],
    checks: list[bool],
) -> None:
    """
    Verify that write methods raise MockWriteDisabledError with correct message.
    Only applies to claimcenter (the only provider with write methods in Phase 2A).
    """
    from backend.app.integration.contracts.claimcenter import (
        ActivityType,
        CreateActivityRequest,
        CreateClaimNoteRequest,
        NoteType,
    )

    write_cases: list[tuple[str, Any]] = []

    note_req = CreateClaimNoteRequest(
        claim_id=_KNOWN_CLAIM_ID,
        note_type=NoteType.GENERAL,
        subject="Validation test note",
        body="Generated by error_validator — not a real note",
        approval_record_id="val-approval-001",
        idempotency_key="val-idem-001",
    )
    write_cases.append(("create_claim_note", lambda: provider.create_claim_note(note_req, _TEST_CTX)))

    act_req = CreateActivityRequest(
        claim_id=_KNOWN_CLAIM_ID,
        activity_type=ActivityType.INVESTIGATION,
        subject="Validation test activity",
        due_date=datetime.date.today(),
        approval_record_id="val-approval-002",
        idempotency_key="val-idem-002",
    )
    write_cases.append(("create_activity", lambda: provider.create_activity(act_req, _TEST_CTX)))

    for method_name, call in write_cases:
        try:
            result = call()
            violations.append(ErrorViolation(
                provider_name=provider_name,
                check_name=f"write_gate:{method_name}",
                violation_type="write_not_disabled",
                detail=(
                    f"{method_name} returned {result!r} instead of raising "
                    f"MockWriteDisabledError. Writes must be disabled in Phase 2A."
                ),
            ))
            checks.append(False)
        except MockWriteDisabledError as e:
            # Verify the message mentions Phase 2B
            if "Phase 2B" not in str(e) and "phase 2b" not in str(e).lower():
                violations.append(ErrorViolation(
                    provider_name=provider_name,
                    check_name=f"write_gate:{method_name}:message",
                    violation_type="wrong_write_disabled_message",
                    detail=f"MockWriteDisabledError message does not mention Phase 2B: '{e}'",
                ))
                checks.append(False)
            else:
                checks.append(True)
        except Exception as exc:
            violations.append(ErrorViolation(
                provider_name=provider_name,
                check_name=f"write_gate:{method_name}",
                violation_type="wrong_exception_type",
                detail=(
                    f"{method_name} raised {type(exc).__name__} instead of "
                    f"MockWriteDisabledError: {exc}"
                ),
            ))
            checks.append(False)


# ---------------------------------------------------------------------------
# Failure mode validation — all providers with a known triggerable method
# ---------------------------------------------------------------------------

def _get_trigger_call(provider_name: str, provider: Any):
    """Return a zero-arg callable that exercises the provider's main read method."""
    ctx = _TEST_CTX
    calls = {
        "claimcenter":  lambda: provider.get_claim(_KNOWN_CLAIM_ID, ctx),
        "policycenter": lambda: provider.get_policy("CA-2024-8812", ctx),
        "edw":          lambda: provider.get_customer_profile("EDW-CUST-10042", ctx),
        "documents":    lambda: provider.get_documents(_KNOWN_CLAIM_ID, ctx),
        "fraud":        lambda: provider.get_fraud_indicators(_KNOWN_CLAIM_ID, ctx),
        "email":        lambda: provider.get_claim_correspondence(_KNOWN_CLAIM_ID, ctx),
    }
    return calls.get(provider_name)


def _validate_failure_modes(
    provider_name: str,
    provider_class: type,
    violations: list[ErrorViolation],
    checks: list[bool],
) -> None:
    """
    For each FailureMode, instantiate a provider with that mode configured
    and verify the correct exception type and retryable flag is raised.
    """
    for failure_mode, expected_exc, expected_retryable in _FAILURE_MODE_EXPECTATIONS:
        sim = SimulationConfig(failure_mode=failure_mode)
        try:
            test_provider = provider_class(sim=sim)
        except TypeError:
            # Provider doesn't accept sim kwarg — skip
            checks.append(True)
            continue

        trigger = _get_trigger_call(provider_name, test_provider)
        if trigger is None:
            checks.append(True)
            continue

        check_name = f"failure_mode:{failure_mode.value}"
        try:
            trigger()
            violations.append(ErrorViolation(
                provider_name=provider_name,
                check_name=check_name,
                violation_type="failure_not_raised",
                detail=f"Expected {expected_exc.__name__} for mode {failure_mode.value}, but no exception raised",
            ))
            checks.append(False)
        except expected_exc as e:
            # Verify retryable flag
            if e.retryable is not expected_retryable:
                violations.append(ErrorViolation(
                    provider_name=provider_name,
                    check_name=f"{check_name}:retryable",
                    violation_type="wrong_retryable_flag",
                    detail=(
                        f"{expected_exc.__name__}.retryable={e.retryable}, "
                        f"expected {expected_retryable}"
                    ),
                ))
                checks.append(False)
            else:
                checks.append(True)
        except MockIntegrationError as e:
            violations.append(ErrorViolation(
                provider_name=provider_name,
                check_name=check_name,
                violation_type="wrong_mock_error_subclass",
                detail=(
                    f"Expected {expected_exc.__name__} for mode {failure_mode.value}, "
                    f"got {type(e).__name__}"
                ),
            ))
            checks.append(False)
        except Exception as exc:
            violations.append(ErrorViolation(
                provider_name=provider_name,
                check_name=check_name,
                violation_type="raw_exception_escaped",
                detail=(
                    f"Raw {type(exc).__name__} escaped provider boundary for mode "
                    f"{failure_mode.value}. Must be wrapped in MockIntegrationError subclass."
                ),
            ))
            checks.append(False)


# ---------------------------------------------------------------------------
# send_email absence check
# ---------------------------------------------------------------------------

def _validate_no_send_email(
    provider_name: str,
    provider: Any,
    violations: list[ErrorViolation],
    checks: list[bool],
) -> None:
    if provider_name != "email":
        return
    if hasattr(provider, "send_email") and callable(getattr(provider, "send_email")):
        violations.append(ErrorViolation(
            provider_name=provider_name,
            check_name="no_send_email",
            violation_type="forbidden_method_present",
            detail=(
                "send_email method must not exist on the email provider. "
                "The platform drafts emails only — sending requires human action."
            ),
        ))
        checks.append(False)
    else:
        checks.append(True)


# ---------------------------------------------------------------------------
# Main entry
# ---------------------------------------------------------------------------

def validate_error_handling(
    provider_name: str,
    provider: Any,
    provider_class: type,
) -> ErrorValidationResult:
    """
    Validate error normalization compliance for a named provider.

    Checks:
      - Write gate raises MockWriteDisabledError (claimcenter only)
      - All 6 failure modes raise the correct exception with correct retryable flag
      - No raw exceptions escape provider boundary
      - send_email absent from email provider

    Args:
        provider_name: canonical name
        provider: provider instance (default SimulationConfig)
        provider_class: the provider class (used to construct failure-mode instances)

    Returns:
        ErrorValidationResult
    """
    violations: list[ErrorViolation] = []
    checks: list[bool] = []

    if provider_name == "claimcenter":
        _validate_write_gate(provider_name, provider, violations, checks)

    _validate_failure_modes(provider_name, provider_class, violations, checks)
    _validate_no_send_email(provider_name, provider, violations, checks)

    return ErrorValidationResult(
        provider_name=provider_name,
        valid=len(violations) == 0 and all(checks),
        violations=violations,
        checks_run=len(checks),
        checks_passed=sum(1 for c in checks if c),
    )


def validate_all_error_handling(
    providers: dict[str, Any],
    provider_classes: dict[str, type],
) -> dict[str, ErrorValidationResult]:
    """Validate error normalization for all named providers."""
    return {
        name: validate_error_handling(name, provider, provider_classes[name])
        for name, provider in providers.items()
    }
